/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as StorageRouteImport } from './routes/storage'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as GuidesExpirationRouteImport } from './routes/guides.expiration'
import { Route as GuidesFeedRouteImport } from './routes/guides.feed'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsBabyRouteImport } from './routes/settings.baby'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsSortRouteImport } from './routes/settings.sort'
import { Route as StorageIndexRouteImport } from './routes/storage.index'
import { Route as StorageIdRouteImport } from './routes/storage.$id'
import { Route as ApiHealthLiveRouteImport } from './routes/api/health/live'
import { Route as ApiHealthReadyRouteImport } from './routes/api/health/ready'
import { Route as ApiHealthStartupRouteImport } from './routes/api/health/startup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesExpirationRoute = GuidesExpirationRouteImport.update({
  id: '/guides/expiration',
  path: '/guides/expiration',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesFeedRoute = GuidesFeedRouteImport.update({
  id: '/guides/feed',
  path: '/guides/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBabyRoute = SettingsBabyRouteImport.update({
  id: '/baby',
  path: '/baby',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSortRoute = SettingsSortRouteImport.update({
  id: '/sort',
  path: '/sort',
  getParentRoute: () => SettingsRoute,
} as any)
const StorageIndexRoute = StorageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StorageRoute,
} as any)
const StorageIdRoute = StorageIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StorageRoute,
} as any)
const ApiHealthLiveRoute = ApiHealthLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => ApiHealthRoute,
} as any)
const ApiHealthReadyRoute = ApiHealthReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => ApiHealthRoute,
} as any)
const ApiHealthStartupRoute = ApiHealthStartupRouteImport.update({
  id: '/startup',
  path: '/startup',
  getParentRoute: () => ApiHealthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/settings': typeof SettingsRouteWithChildren
  '/stats': typeof StatsRoute
  '/storage': typeof StorageRouteWithChildren
  '/api/health': typeof ApiHealthRouteWithChildren
  '/guides/expiration': typeof GuidesExpirationRoute
  '/guides/feed': typeof GuidesFeedRoute
  '/settings/baby': typeof SettingsBabyRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/sort': typeof SettingsSortRoute
  '/storage/$id': typeof StorageIdRoute
  '/settings/': typeof SettingsIndexRoute
  '/storage/': typeof StorageIndexRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/health/startup': typeof ApiHealthStartupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/stats': typeof StatsRoute
  '/api/health': typeof ApiHealthRouteWithChildren
  '/guides/expiration': typeof GuidesExpirationRoute
  '/guides/feed': typeof GuidesFeedRoute
  '/settings/baby': typeof SettingsBabyRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/sort': typeof SettingsSortRoute
  '/storage/$id': typeof StorageIdRoute
  '/settings': typeof SettingsIndexRoute
  '/storage': typeof StorageIndexRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/health/startup': typeof ApiHealthStartupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/settings': typeof SettingsRouteWithChildren
  '/stats': typeof StatsRoute
  '/storage': typeof StorageRouteWithChildren
  '/api/health': typeof ApiHealthRouteWithChildren
  '/guides/expiration': typeof GuidesExpirationRoute
  '/guides/feed': typeof GuidesFeedRoute
  '/settings/baby': typeof SettingsBabyRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/sort': typeof SettingsSortRoute
  '/storage/$id': typeof StorageIdRoute
  '/settings/': typeof SettingsIndexRoute
  '/storage/': typeof StorageIndexRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/health/startup': typeof ApiHealthStartupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/settings'
    | '/stats'
    | '/storage'
    | '/api/health'
    | '/guides/expiration'
    | '/guides/feed'
    | '/settings/baby'
    | '/settings/notifications'
    | '/settings/sort'
    | '/storage/$id'
    | '/settings/'
    | '/storage/'
    | '/api/health/live'
    | '/api/health/ready'
    | '/api/health/startup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/stats'
    | '/api/health'
    | '/guides/expiration'
    | '/guides/feed'
    | '/settings/baby'
    | '/settings/notifications'
    | '/settings/sort'
    | '/storage/$id'
    | '/settings'
    | '/storage'
    | '/api/health/live'
    | '/api/health/ready'
    | '/api/health/startup'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/settings'
    | '/stats'
    | '/storage'
    | '/api/health'
    | '/guides/expiration'
    | '/guides/feed'
    | '/settings/baby'
    | '/settings/notifications'
    | '/settings/sort'
    | '/storage/$id'
    | '/settings/'
    | '/storage/'
    | '/api/health/live'
    | '/api/health/ready'
    | '/api/health/startup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  StatsRoute: typeof StatsRoute
  StorageRoute: typeof StorageRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRouteWithChildren
  GuidesExpirationRoute: typeof GuidesExpirationRoute
  GuidesFeedRoute: typeof GuidesFeedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/expiration': {
      id: '/guides/expiration'
      path: '/guides/expiration'
      fullPath: '/guides/expiration'
      preLoaderRoute: typeof GuidesExpirationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/feed': {
      id: '/guides/feed'
      path: '/guides/feed'
      fullPath: '/guides/feed'
      preLoaderRoute: typeof GuidesFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/baby': {
      id: '/settings/baby'
      path: '/baby'
      fullPath: '/settings/baby'
      preLoaderRoute: typeof SettingsBabyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/sort': {
      id: '/settings/sort'
      path: '/sort'
      fullPath: '/settings/sort'
      preLoaderRoute: typeof SettingsSortRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/storage/': {
      id: '/storage/'
      path: '/'
      fullPath: '/storage/'
      preLoaderRoute: typeof StorageIndexRouteImport
      parentRoute: typeof StorageRoute
    }
    '/storage/$id': {
      id: '/storage/$id'
      path: '/$id'
      fullPath: '/storage/$id'
      preLoaderRoute: typeof StorageIdRouteImport
      parentRoute: typeof StorageRoute
    }
    '/api/health/live': {
      id: '/api/health/live'
      path: '/live'
      fullPath: '/api/health/live'
      preLoaderRoute: typeof ApiHealthLiveRouteImport
      parentRoute: typeof ApiHealthRoute
    }
    '/api/health/ready': {
      id: '/api/health/ready'
      path: '/ready'
      fullPath: '/api/health/ready'
      preLoaderRoute: typeof ApiHealthReadyRouteImport
      parentRoute: typeof ApiHealthRoute
    }
    '/api/health/startup': {
      id: '/api/health/startup'
      path: '/startup'
      fullPath: '/api/health/startup'
      preLoaderRoute: typeof ApiHealthStartupRouteImport
      parentRoute: typeof ApiHealthRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsBabyRoute: typeof SettingsBabyRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsSortRoute: typeof SettingsSortRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsBabyRoute: SettingsBabyRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsSortRoute: SettingsSortRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface StorageRouteChildren {
  StorageIdRoute: typeof StorageIdRoute
  StorageIndexRoute: typeof StorageIndexRoute
}

const StorageRouteChildren: StorageRouteChildren = {
  StorageIdRoute: StorageIdRoute,
  StorageIndexRoute: StorageIndexRoute,
}

const StorageRouteWithChildren =
  StorageRoute._addFileChildren(StorageRouteChildren)

interface ApiHealthRouteChildren {
  ApiHealthLiveRoute: typeof ApiHealthLiveRoute
  ApiHealthReadyRoute: typeof ApiHealthReadyRoute
  ApiHealthStartupRoute: typeof ApiHealthStartupRoute
}

const ApiHealthRouteChildren: ApiHealthRouteChildren = {
  ApiHealthLiveRoute: ApiHealthLiveRoute,
  ApiHealthReadyRoute: ApiHealthReadyRoute,
  ApiHealthStartupRoute: ApiHealthStartupRoute,
}

const ApiHealthRouteWithChildren = ApiHealthRoute._addFileChildren(
  ApiHealthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  SettingsRoute: SettingsRouteWithChildren,
  StatsRoute: StatsRoute,
  StorageRoute: StorageRouteWithChildren,
  ApiHealthRoute: ApiHealthRouteWithChildren,
  GuidesExpirationRoute: GuidesExpirationRoute,
  GuidesFeedRoute: GuidesFeedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
